const lyrics = [
        { time: 1, words: 'Ase LeuMas,' },
        { time: 7, words: 'Zawu zoba zoba Zawu (ey)' },
        { time: 9.6, words: 'Zaukape ine sindipanga' },
        { time: 12, words: 'Zaukape ine sindipanga' },
        { time: 14, words: 'Zauzoba sindipanga' },
        { time: 16, words: 'Zaukape ine sindipanga' },
        { time: 22, words: 'Zondipinga ine mmm mmm' },
        { time: 26, words: 'Zondiyenda mbali ine (eish)' },
        { time: 27.7, words: 'Ndikati mmm mmm, mmm-mmm (kuno ayi)' },
        { time: 31, words: 'mmm mmm, mmm-mmm (ine)' },
        { time: 34.3, words: 'mmm mmm, mmm-mmm (kuno ayi)' },
        { time: 40, words: 'Ngati isali trans ID ine mmm mmm' },
        { time: 45, words: 'Can you do me a favour ine mmm mmm' },
        { time: 50, words: 'Iwe cross yowuluka ine mmm mmm' },
        { time: 54, words: 'Zongobwela muli boys yokha yokha kuno mmm mmm' },
        { time: 57, words: 'Inu shasha naye ndi munthu' },
        { time: 59.5, words: 'Kaya local chicken bolani nkhuku' },
        { time: 62.2, words: 'Kumamwela ndi ma mmm mmm' },
        { time: 64.6, words: 'Macheza amakoma tili two two' },
        { time: 66.5, words: 'Zamijedu kuno mmm mmm (kuno ayi)' },
        { time: 70, words: 'zamabodza kuno mmm mmm' },
        { time: 72, words: 'zamaluzi pano mmm mmm' },
        { time: 75, words: 'Tiku chaser bag sizibukhu' },
        { time: 76.75, words: 'ay yay yay yay yay yay' },
        { time: 80, words: 'Zondipinga ine mmm mmm' },
        { time: 84, words: 'Zondiyenda mbali ine mmm mmm (eish)' },
        { time: 88.5, words: 'Boss zotipinga ife mmm mmm' },
        { time: 92, words: 'Inu, zotiyenda mbali ife' },
    ];